[package]
name = "lock_canister"
version = "1.0.0"
authors = ["DAOPad Team"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.15"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
candid-extractor = "0.1.6"