[package]
name = "lock_canister"
version = "1.0.0"
authors = ["DAOPad Team"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.18"
ic-cdk = "0.17.2"
serde = { version = "1.0", features = ["derive"] }

